<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Deskrip extends CI_Controller {
    
      public function __construct()
    {
        parent::__construct();
        is_access_controll();
    }

    
    
    public function index() {
        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
        $data['title'] = 'Manage Deskrip';
        $data['titleM'] = ['Deskrip', 'TMDB'];
            $this->load->view('templates/header', $data);
            $this->load->view('templates/sidebar');
            $this->load->view('templates/topbar', $data);
            $this->load->view('deskrip/index');
            $this->load->view('templates/footer');
        
    }

    public function index_tvdb() {
        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
        $data['title'] = 'Manage Deskrip';
        $data['titleM'] = ['Deskrip', 'TVDB'];
            $this->load->view('templates/header', $data);
            $this->load->view('templates/sidebar');
            $this->load->view('templates/topbar', $data);
            $this->load->view('deskrip/index_tvdb');
            $this->load->view('templates/footer');
        
    }

    public function tmdb() {
        $data = [
            'tvid' => $this->input->get('id'),
            'season' => $this->input->get('season'),
            'episode' => $this->input->get('episode'),
            'link' => 'http://show.online-tvs.com/tv'
        ];

        $url3 = 'https://api.themoviedb.org/3/tv/' . $data['tvid'] . '/external_ids?api_key=6c147458a042d7ec288e88f63c986e4c&language=en-US';
        $url2 = 'https://api.themoviedb.org/3/tv/' . $data['tvid'] . '/season/' . $data['season'] . '/episode/' . $data['episode'] . '?api_key=6c147458a042d7ec288e88f63c986e4c&language=en-US';
        $url = 'https://api.themoviedb.org/3/tv/' . $data['tvid'] . '?api_key=6c147458a042d7ec288e88f63c986e4c&language=en-US';





        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
        $data['title'] = 'Manage Deskrip';
        $data['titleM'] = ['Deskrip', 'TMDB'];
        $data['result_id'] = $this->_searchByTvId($url);
        $data['result_detail'] = $this->_searchByTvId($url2);
        $data['ex_id'] = $this->_searchByTvId($url3);
        
        $this->form_validation->set_rules('id' , 'tmdb_id' , 'required|numeric');
        $this->form_validation->set_rules('season' , 'season' , 'required|numeric');
        $this->form_validation->set_rules('episode' , 'episode' , 'required|numeric');
        if ($this->form_validation->run() == false) {
            $this->load->view('templates/header', $data);
            $this->load->view('templates/sidebar', $data);
            $this->load->view('templates/topbar', $data);
            $this->load->view('deskrip/tmdb', $data);
            $this->load->view('templates/footer');
        }
    }

    public function tvdb() {
        $data = [
            'tvdbid' => $this->input->get('id'),
            'season' => $this->input->get('season'),
            'episode' => $this->input->get('episode'),
            'link' => 'http://show.online-tvs.com/series'
        ];

        $url = 'https://api.thetvdb.com/series/' . $data['tvdbid'];
        $data['result_tvdbId'] = $this->_searchTvDbById($url);
        //  var_dump($data['result_tvdbId'] = $this->_searchTvDbById($url)); die;
        

        

        $data['user'] = $this->db->get_where('user', ['email' => $this->session->userdata('email')])->row_array();
        $data['title'] = 'Manage Deskrip';
        $data['titleM'] = ['Deskrip', 'TVDB'];
        $data['result_id'] = $this->_searchByTvId($url);
        $this->load->view('templates/header', $data);
        $this->load->view('templates/sidebar', $data);
        $this->load->view('templates/topbar', $data);
        $this->load->view('deskrip/tvdb', $data);
        $this->load->view('templates/footer');
    }

    


    

    private function _searchByTvId($url){
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $result = curl_exec($ch);
    curl_close($ch);
    return json_decode($result, true);
    }


    public function _searchTvDbById($url) {

    
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTM2MzQzNzQsImlkIjoiY2ktYWRtaW4iLCJvcmlnX2lhdCI6MTU5MzAyOTU3NCwidXNlcmlkIjoyMjMxNjk4LCJ1c2VybmFtZSI6InJpZmFsbnVyY2h5YTJ4ajMifQ.IkN9AWI_Aee1uAoEkv5o1yLqB_Y6pIx0ya7lEjDYEpOw2DVJcYFEve_bYgv5UaT8AqwQOnOlaJLVL8P5Yw2rdHtXOkXSo2mtPP0ILF6qlL1DynTLlVqbToku2Whf4ld5UFfw41tebgj-soDI9hg3STU9jxwoLJhDKd8b8DGRednyHmUYWTJEbevwjyMMJRJ0pcKxVLqy6l1tmM-nxZ8a3geBZRzb8xOYMGsApK8FXf-NTNSylbHbmT-QFMKDlMOlZJm0u8BU3IxopheakVdBM9HGhcxh_dDm9bCNJntW6jWFlQg2iz6-UC_8nU3M_mwtMX0vNYSYn7e0uIqToQu6ow';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
return json_decode($result , true);

 
    
    }
}
