module.exports = {
    products: [
        {
            _id:'1',
            name:'Table dyznis',
            category:'Tables',
            image: '/images/product1.png',
            price: 6023,
            brand: 'DIC',
            rating: 5.0,
            numReviews: 10,
            countInStock: 6,           
        },
        {
            _id:'2',
            name:'Repsont Da',
            category:'Tables',
            image: '/images/product2.png',
            price: 5000,
            brand: 'DIC',
            rating: 4.9,
            numReviews: 10,
            countInStock: 6,           
        },
        {
            _id:'3',
            name:'Yuiresna sar',
            category:'Tables',
            image: '/images/product3.png',
            price: 1000,
            brand: 'DIC',
            rating: 4.7,
            numReviews: 10,
            countInStock: 6,           
        },
        {
            _id:'4',
            name:'Likesa Astsas',
            category:'Tables',
            image: '/images/product4.png',
            price: 60,
            brand: 'DIC',
            rating: 5.0,
            numReviews: 10,
            countInStock: 6,           
        },
        {
            _id:'5',
            name:'Gugregrin atar',
            category:'Tables',
            image: '/images/product5.png',
            price: 2399,
            brand: 'DIC',
            rating: 4.0,
            numReviews: 10,
            countInStock: 6,           
        },
    ],
}